apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: NodePort
  selector:
    app: result
  ports:
    - name: result-service
      port: 80
      targetPort: 80
      nodePort: 30081
