apiVersion: v1
kind: Service
metadata:
    name: api-service
spec:
    type: ClusterIP
    selector:
        app: api
    ports:
        - port: 8080 #Service port
          targetPort: 5678 #Pod port
