apiVersion: apps/v1
kind: Deployment
metadata:
    name: web-deployment
    labels:
        app: web
spec:
    replicas: 2
    selector:
        matchLabels:
            app: web
    template:
        metadata:
            labels:
                app: web
        spec:
            containers:
                - name: web-container
                  # Frontend that proxies to backend via ClusterIP
                  image: nginx:alpine
                  ports:
                      - containerPort: 80
                  command: ["/bin/sh", "-c"]
                  args:
                      - |
                        echo 'server {
                            listen 80;
                            location / {
                                proxy_pass http://api-service:8080/;
                            }
                        }' > /etc/nginx/conf.d/default.conf
                        nginx -g "daemon off;"
