apiVersion: v1
kind: Service
metadata:
    name: web-service
spec:
    type: NodePort
    selector:
        app: web
    ports:
        - port: 80 #Service port
          targetPort: 80 #Pod port
          nodePort: 30080 #Node port
